#created on: 19-Nov-2009
#author	: Mei Yii Lim

package MemoryProcesses

#list any import classes here.
import FAtiMA.memory.episodicMemory.ActionDetail;

#declare any global variables here

/*rule "same id"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($i1 : ID) from $q.actionDetail
		$cad: CandidateEvent(ID != true)
		$ad: ActionDetail(ID == $i1) from $cad.actionDetail	
	then		
		modify ($cad)
		{
			increasePhase(), 
			setExtension("id"),
			setID(true),	
			updateEvaluation(1.0)	
		}
		System.out.println("ID " + $i1);
		System.out.println("same id " + $ad.getID());
end

rule "different id"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($i1 : ID) from $q.actionDetail
		$cad: CandidateEvent(ID != true)
		$ad: ActionDetail(ID != $i1) from $cad.actionDetail	
	then		
		modify ($cad)
		{
			increasePhase(), 
			setExtension("id"),
			setID(true),	
			updateEvaluation(0.9)	
		}
		System.out.println("ID " + $i1);
		System.out.println("different id " + $ad.getID());
end*/

rule "same subject"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($s1 : subject) from $q.actionDetail
		$cad: CandidateEvent(subject != true, phase != $q.numField)
		$ad: ActionDetail(subject == $s1) from $cad.actionDetail	
	then		
		modify ($cad)
		{
			increasePhase(), 
			setExtension("subject"),
			setSubject(true),	
			updateEvaluation(1.0f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("same subject " + $ad.getID());
end

rule "different subject"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($s1 : subject) from $q.actionDetail
		$cad: CandidateEvent(subject != true, phase != $q.numField)
		$ad: ActionDetail(subject != $s1) from $cad.actionDetail	
	then		
		modify ($cad)
		{
			increasePhase(), 
			setExtension("subject"),
			setSubject(true),	
			updateEvaluation(0.8f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("different subject " + $ad.getID());
end

rule "same target"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($t1 : target) from $q.actionDetail
		$cad: CandidateEvent(target != true, phase != $q.numField)
		$ad: ActionDetail(target == $t1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("target"),
			setTarget(true),
			updateEvaluation(1.0f)			
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("same target " + $ad.getID());
end

rule "different target"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($t1 : target) from $q.actionDetail
		$cad: CandidateEvent(target != true, phase != $q.numField)
		$ad: ActionDetail(target != $t1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("target"),
			setTarget(true),
			updateEvaluation(0.8f)			
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("different target " + $ad.getID());
end

rule "same action"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($a1 : action) from $q.actionDetail
		$cad: CandidateEvent(action != true, phase != $q.numField)
		$ad: ActionDetail(action == $a1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("action"),
			setAction(true),
			updateEvaluation(1.0f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("same action " + $ad.getID());
end

rule "different action"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($a1 : action) from $q.actionDetail
		$cad: CandidateEvent(action != true, phase != $q.numField)
		$ad: ActionDetail(action != $a1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("action"),
			setAction(true),
			updateEvaluation(0.8f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("different action " + $ad.getID());
end

rule "same location"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($l1 : location) from $q.actionDetail
		$cad: CandidateEvent(location != true, phase != $q.numField)
		$ad: ActionDetail(location == $l1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("location"),
			setLocation(true),
			updateEvaluation(1.0f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("same location " + $ad.getID());
end

rule "different location"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($l1 : location) from $q.actionDetail
		$cad: CandidateEvent(location != true, phase != $q.numField)
		$ad: ActionDetail(location != $l1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("location"),
			setLocation(true),
			updateEvaluation(0.8f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("different location " + $ad.getID());
end

rule "same emotion"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($e1 : emotion) from $q.actionDetail
		$cad: CandidateEvent(emotion != true, phase != $q.numField)
		$ad: ActionDetail(emotion == $e1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("emotion"),
			setEmotion(true),
			updateEvaluation(1.0f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("same emotion " + $ad.getID());
end

rule "different emotion"
	no-loop true
	when
		$q: CCQuery()
		$qad: ActionDetail($e1 : emotion) from $q.actionDetail
		$cad: CandidateEvent(emotion != true, phase != $q.numField)
		$ad: ActionDetail(emotion != $e1) from $cad.actionDetail	
	then
		modify ($cad)
		{
			increasePhase(), 
			setExtension("emotion"),
			setEmotion(true),
			updateEvaluation(1.0f)		
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("different emotion " + $ad.getID());
end

rule "end match" 
	no-loop true
	when 
		$q: CCQuery()
		$cad: CandidateEvent(phase == $q.numField)
		$ad: ActionDetail() from $cad.actionDetail	
	then
		modify ($q)
		{
			setResults($ad.getID(), $cad.getEvaluation())
		}
		System.out.println("Evaluation " + $cad.getEvaluation());
		System.out.println("end match " + $ad.getID());
		retract ($cad);
end