package FAtiMA.Core.OCCAffectDerivation;

public enum OCCAppraisalVariables {
	DESIRABILITY, 
	PRAISEWORTHINESS,
	DESFOROTHER,
	LIKE,
    GOALCONDUCIVENESS,
    SUCCESSPROBABILITY,
    FAILUREPROBABILITY,
	GOALSTATUS;
}
