#!/usr/bin/env python

from faces import *
from math import *
import os 
import sys

if sys.argv[1] == "-h":
	print("disp_pca pcafile width height starteigenface endeigenface gain")
	exit(0)

pca = load_pca(sys.argv[1])
w=int(sys.argv[2])
h=int(sys.argv[3])

img = smp.toimage( make_eigenfaces_image(w,h,pca,int(sys.argv[4]),int(sys.argv[5]),float(sys.argv[6])))
img.show()  
